[book]
title = "Circles Handbook"
author = "CirclesUBI"
description = "Circles handbook for users, communities and developers"
src = "docs"
language = "en"

[rust]
edition = "2018"

[build]
build-dir = "public"
create-missing = false

[output.html]
additional-css = ["styles.css"]

[output.html.search]
limit-results = 15
